name: docker

on:
  push:
    branches:
      - "main"

jobs:
  main:
    name: Dockerhub push
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: docker/build-push-action@v1.1.1
        name: push
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: daggy1234/dagpi-image
          tag_with_ref: true